name: Build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

      - name: Install dependencies
        run: go mod tidy

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run unit tests
        run: go install github.com/go-delve/delve/cmd/dlv@latest && go test ./... -v -covermode=count -coverprofile=coverage.txt
